require.config({baseUrl:"/js",paths:{jquery:"libs/jquery/jquery-min",underscore:"libs/underscore/underscore",backbone:"libs/backbone/backbone",text:"libs/require/text",less:"libs/less",iscroll:"libs/iscroll",base64:"libs/base64",mustache:"libs/mustache/mustache"}});window.storage=localStorage;window.getMessage=chrome.i18n.getMessage;var extensionVersion=chrome.app.getDetails().version;
"undefined"!==typeof chrome.runtime&&chrome.runtime.onInstalled.addListener(function(e){console.log("extension install/updated. details: ",e);storage.setItem("isNewInstall",e.reason);"install"==e.reason&&storage.setItem("forceLogout","true")});
require("jquery,underscore,collections/task,collections/category,server/auth,server/sync,chrome/helpers,helpers/alert,constants,config/user".split(","),function(e,K,B,C,o,L,p,D,M,E){function q(){h&&D.popUpReminder(i,c)}function w(a,b,j,d){var e=a.alert||null,f=a.linkUrl||null;if(h){console.log("task details:",a,"due date:",c.generateDueDate(b));c.create({title:a.title,categoryId:i.getDefaultCategory().id,dueDate:+c.generateDueDate(b),alert:e,linkUrl:f},{success:function(){typeof j==="function"&&j.apply(this,
arguments)},error:function(a){typeof d==="function"&&d.apply(this,arguments);if(a.status==409){alert("You must log in to Any.DO first.");typeof d==="function"&&d({errorReason:"loggedOut"})}else{alert("There was an error with our servers... Please try again later. Error: "+a.status);typeof d==="function"&&d()}}})}else typeof d==="function"&&d({errorReason:"loggedOut"})}function F(){var a=storage.getItem("userPuid");if(a!=null){r("AnyDO-Puid",a);s()}else e.ajax({url:ME_URL,type:"get",xhrFields:{withCredentials:true},
crossDomain:true,success:function(a){storage.setItem("userPuid",a.id);r("AnyDO-Puid",a.id);s()},error:s})}function l(){return((1+Math.random())*65536|0).toString(16).substring(1)}function r(a,b){e(document).on("ajaxSend",function(j,d){d.setRequestHeader(a,b)})}function G(){function a(a,b,c){a=a.linkUrl||a.selectionText||a.srcUrl||a.pageUrl;_gaq.push(["_trackEvent","Context Menu","Task Added"]);w({title:a},c)}console.log("Background page: initializing context menu.");chrome.contextMenus.removeAll();
var b=chrome.contextMenus.create({type:"normal",title:getMessage("context_add_to_anydo"),contexts:["all"]});chrome.contextMenus.create({parentId:b,type:"normal",title:getMessage("date_today"),contexts:["all"],onclick:function(b,d){a(b,d,DATE_CATEGORY_TODAY)}});chrome.contextMenus.create({parentId:b,type:"normal",title:getMessage("date_tomorrow"),contexts:["all"],onclick:function(b,d){a(b,d,DATE_CATEGORY_TOMORROW)}});chrome.contextMenus.create({parentId:b,type:"normal",title:getMessage("date_upcoming"),
contexts:["all"],onclick:function(b,d){a(b,d,DATE_CATEGORY_UPCOMING)}});chrome.contextMenus.create({parentId:b,type:"normal",title:getMessage("date_someday"),contexts:["all"],onclick:function(b,d){a(b,d,DATE_CATEGORY_SOMEDAY)}})}function m(a){h&&(a===void 0?p.updateTaskCounter(c.getLeftTasks().length):p.updateTaskCounter(a))}function x(){var a=[];a[0]=g.getGmailActive()?"1":"0";a[1]=g.getCalendarDay().toString();a[2]=g.getView()==VIEW_BY_DUE_DATE?"0":g.getView()==VIEW_BY_CATEGORY?"1":g.getView()==
VIEW_BY_PRIORITY?"2":"#";console.log("bitFlag",a.join(""));return a.join("")}function s(){var a=storage.getItem("isNewInstall");console.log("Install reason is",a);if(a=="install"){console.log("reporting installation for user",storage.getItem("userPuid"));e.ajax({url:ME_URL,type:"put",contentType:"application/json",data:JSON.stringify({id:storage.getItem("userPuid"),name:storage.getItem("userName"),instDetails:{installationId:btoa((l()+l()+"-"+l()+"-"+l()).slice(2)),version_code:extensionVersion,platform:"WEB",
userSettings:x()}}),crossDomain:true});a=new Date;a=""+a.getUTCFullYear()+(a.getUTCMonth()+1)+a.getUTCDate();_gaq.push(["_setCustomVar",5,"Installed",a,1]);storage.removeItem("isNewInstall");y()}}function n(){_gaq.push(["_setCustomVar",2,"Settings Flags",x(),1]);if(h)console.log("Initialization already done.");else{console.log("Background page: logging in.");F();G();c=new B;i=new C;c.bind("reset",function(){h=true;m();q()});i.fetch();c.fetch()}}function y(){h=false;storage.clear();console.log("Background page: logging out.");
p.updateTaskCounter(0);chrome.contextMenus.removeAll()}function H(a){setTimeout(function(){console.log("Recovering visibility... (toggling tab)");if(k[a.id]===void 0){console.log("Tab not defined. Let's activate it. Man you click fast!");k[a.id]=true}k[a.id]&&chrome.tabs.sendRequest(a.id,{action:"toggleTab",src:document.location.origin+"/index.html",hidden:t[a.id]})},1E3)}function I(a,b){console.log("Injecting code...");chrome.tabs.executeScript(a.id,{file:"js/chrome/inject.js"},function(){b()})}
function J(a){if(u[a.id]){console.log("Toggling to code which was already injected");z(a)}else{u[a.id]=true;a.status=="complete"&&chrome.tabs.executeScript(a.id,{file:"js/chrome/inject.js"},function(){console.log("Toggling after script injected...");z(a)})}}function z(a){console.log("Toggling tab...");k[a.id]=!k[a.id];chrome.tabs.sendRequest(a.id,{action:"toggleTab",src:document.location.origin+"/index.html",hidden:t[a.id]})}function v(){f==null?A():chrome.windows.get(f.id,function(a){if(a){console.log("Popup already exists, not opening a new one.");
chrome.windows.update(f.id,{focused:true})}else A()})}function A(){chrome.windows.create({url:"/index.html#popup",width:286,height:600,focused:true,type:"panel"},function(a){f=a})}window._gaq=window._gaq||[];_gaq.push(["_setAccount",SERVER_API_URL.indexOf("sm-prod")>-1?"UA-28645084-1":"UA-28645272-1"]);_gaq.push(["_setCustomVar",1,"Chrome Version Code",extensionVersion,1]);r("AnyDO-Version",extensionVersion);var c,i,u={},k={},t={},f=null,h=false,g=new E;window.trackPageview=function(a){_gaq.push(["_trackPageview",
a])};window.track=function(a){a=e.map(a,function(a){return a});switch(a.length){case 0:case 1:console.error("Google Analytics: You should use at least a Category and an Action");break;case 2:_gaq.push(["_trackEvent",a[0],a[1]]);break;case 3:_gaq.push(["_trackEvent",a[0],a[1],a[2]]);break;case 4:_gaq.push(["_trackEvent",a[0],a[1],a[2],a[3]])}};OPEN_POPUP?chrome.browserAction.setPopup({popup:"/index.html"}):chrome.browserAction.onClicked.addListener(function(a){console.log("Received click on tab",a);
if(a.url.search(/^chrome/)>=0)v();else{if(f){chrome.windows.remove(f.id);f=null}J(a)}});chrome.tabs.onActiveChanged.addListener(function(a){chrome.tabs.sendRequest(a,{action:"refreshTab"})});chrome.extension.onRequest.addListener(function(a,b,j){switch(a.action){case "facebookConnectComplete":o.logInWithFacebook(a.access_token,function(){window.storage.setItem("access_token",a.access_token);n();OPEN_POPUP&&v();chrome.extension.sendRequest({action:"facebookConnectComplete",success:true})},function(){alert("There was an error logging in with Facebook. Please try again.");
window.storage.removeItem("access_token");chrome.tabs.getSelected(null,function(a){chrome.tabs.sendRequest(a.id,{action:"facebookConnectComplete",success:false})})});break;case "logIn":n();break;case "logOut":y();break;case "alert":switch(a.alert){case "done":if(c)if(c.get(a.id)){c.get(a.id).markAsChecked();chrome.extension.sendRequest({action:"refreshTab"})}else console.error("can't find task ID!");else console.error("Can't find the tasks collection!");break;case "snooze":c?c.get(a.id).snoozeTask(6E4*
a.minutes):console.error("Can't find the tasks collection!");break;case "dismiss":c.get(a.id).dismissAlert(function(){chrome.extension.sendRequest({action:"refreshTab"})})}m();break;case "refresh":q();m();break;case "report":console.log("reporting to GA",a.report);_gaq.push(a.report);break;case "track":track(a.track);break;case "trackPageview":trackPageview(a.track);break;case "openPage":console.log("Opening external page "+a.url);chrome.tabs.create({url:a.url});break;case "updateBadge":m(a.numTasks);
break;case "updateHiddenStatus":t[b.tab.id]=a.hidden;console.log("tab",b.tab.id,"tabsHidden[sender.tab.id]",a.hidden);break;case "popupWindow":v();break;case "closePopup":if(f){chrome.windows.remove(f.id);f=null}}j()});chrome.tabs.onUpdated.addListener(function(a,b,c){if(b.status=="complete"&&c.url.search(/^chrome/)!=0&&u[c.id]){console.log("on update completed and already inject and not a chrome page");I(c,function(){H(c)})}});chrome.extension.onMessage.addListener(function(a,b,c){if(a.type=="gmailInit"){n();
var d=false;if(g.getGmailActive(GMAIL_ACTIVE)&&!storage.getItem("gmail-tour")){d=true;storage.setItem("gmail-tour",true)}c({active:true,tour:d})}a.type=="isGmailActive"&&c({gmail:g.getGmailActive(GMAIL_ACTIVE),gmailNext:g.getGmailActive(GMAIL_NEXT_ACTIVE)});if(a.type=="gmailAddTask"){b=window[a.dateCategory];if(!b)b=a.dateCategory;w(a.data,b,function(b,d){_gaq.push(["_trackEvent","Gmail","Task Added"]);console.log("added from gmail",d);if(a.data.hasOwnProperty("originalSuggestion")){e.post("http://afternoon-earth-1266.herokuapp.com/raw_email_analytics",
{added_as:a.data.title,suggestion:a.data.originalSuggestion,conversation:a.data.conversation});console.log({added_as:a.data.title,suggestion:a.data.originalSuggestion,conversation:a.data.conversation})}c({success:true})},function(a){a=e.extend({},a,{success:false});c(a)});return true}a.type=="gmailCalendarPick"&&chrome.tabs.sendMessage(b.tab.id,a)});(function(){var a=document.createElement("script");a.type="text/javascript";a.async=true;a.src="https://ssl.google-analytics.com/ga.js";var b=document.getElementsByTagName("script")[0];
b.parentNode.insertBefore(a,b)})();window.onerror=function(a,b,c){_gaq.push(["_trackEvent","Exceptions","Application","["+b+" ("+c+")] "+a,null,true])};console.log("Setting up timers...");setInterval(function(){if(h){i.fetch();c.fetch()}},18E5);setInterval(q,6E4);console.log("Background page initialized successfully.");o.credentialsSaved()&&o.logInUsingStoredCredentials(function(){n()},function(){console.log("Can't log in for some reason.")})});